export const mathsQuestions = [
  { text: "If p → q is a conditional, its contrapositive is:", options: ["¬q → ¬p", "¬p → ¬q", "q → p", "p → ¬q"], correctOptionIndex: 0, solutionText: "Contrapositive of p→q is ¬q→¬p (always equivalent to original)." },
  { text: "The inverse of matrix A = [[1,0],[0,1]] is:", options: ["[[1,0],[0,1]]", "[[0,1],[1,0]]", "[[-1,0],[0,-1]]", "Does not exist"], correctOptionIndex: 0, solutionText: "The inverse of the identity matrix I is I itself." },
  { text: "If A is a 3×3 matrix with det(A) = 4, then det(2A) =", options: ["32", "8", "64", "4"], correctOptionIndex: 0, solutionText: "det(kA) = k³·det(A) for 3×3 matrix. det(2A) = 2³×4 = 32." },
  { text: "Principal value of sin⁻¹(1/2) is:", options: ["π/6", "π/3", "π/4", "π/2"], correctOptionIndex: 0, solutionText: "sin(π/6) = 1/2, and π/6 ∈ [-π/2, π/2] → principal value = π/6." },
  { text: "cos⁻¹(-1) = ?", options: ["π", "0", "π/2", "-π"], correctOptionIndex: 0, solutionText: "cos(π) = -1, and π ∈ [0, π] → cos⁻¹(-1) = π." },
  { text: "The angle between lines y = 3x + 1 and y = -3x + 2 is:", options: ["90°", "60°", "45°", "30°"], correctOptionIndex: 0, solutionText: "m₁×m₂ = 3×(-3) = -9 ≠ -1; use tanθ = |(m₁-m₂)/(1+m₁m₂)|." },
  { text: "The combined equation of the pair of lines x = 0 and y = 0 is:", options: ["xy = 0", "x + y = 0", "x² + y² = 0", "x² - y² = 0"], correctOptionIndex: 0, solutionText: "x = 0 and y = 0 combined: xy = 0." },
  { text: "Equation of a circle with centre (2, -3) and radius 4 is:", options: ["(x-2)² + (y+3)² = 16", "(x+2)² + (y-3)² = 16", "(x-2)² + (y-3)² = 16", "(x+2)² + (y+3)² = 16"], correctOptionIndex: 0, solutionText: "(x-h)² + (y-k)² = r²; (x-2)² + (y+3)² = 16." },
  { text: "The focus of the parabola y² = 4ax is:", options: ["(a, 0)", "(0, a)", "(-a, 0)", "(0, -a)"], correctOptionIndex: 0, solutionText: "Standard parabola y² = 4ax has focus at (a, 0)." },
  { text: "Eccentricity of an ellipse x²/16 + y²/9 = 1 is:", options: ["√7/4", "√7/3", "3/4", "4/3"], correctOptionIndex: 0, solutionText: "a²=16, b²=9; c²=a²-b²=7; e=c/a=√7/4." },
  { text: "If |a⃗| = 3, |b⃗| = 4 and a⃗·b⃗ = 0, then |a⃗ + b⃗| =", options: ["5", "7", "1", "12"], correctOptionIndex: 0, solutionText: "|a+b|² = |a|² + 2a·b + |b|² = 9+0+16=25 → |a+b| = 5." },
  { text: "The cross product a⃗ × a⃗ =", options: ["0⃗", "|a⃗|²", "1", "a⃗"], correctOptionIndex: 0, solutionText: "a⃗ × a⃗ = |a|²sin(0°) = 0; also any vector crossed with itself is zero vector." },
  { text: "Direction cosines of z-axis are:", options: ["(0, 0, 1)", "(1, 0, 0)", "(0, 1, 0)", "(1, 1, 1)"], correctOptionIndex: 0, solutionText: "z-axis has direction (0,0,1), so l=0, m=0, n=1." },
  { text: "lim(x→0) sin(x)/x =", options: ["1", "0", "∞", "-1"], correctOptionIndex: 0, solutionText: "Standard limit: lim(x→0) sinx/x = 1." },
  { text: "lim(x→0) (eˣ - 1)/x =", options: ["1", "e", "0", "∞"], correctOptionIndex: 0, solutionText: "By L'Hôpital or expansion: lim(x→0)(eˣ-1)/x = 1." },
  { text: "d/dx (sin x) =", options: ["cos x", "-cos x", "sin x", "-sin x"], correctOptionIndex: 0, solutionText: "Standard derivative: d/dx(sin x) = cos x." },
  { text: "d/dx (xⁿ) =", options: ["nxⁿ⁻¹", "xⁿ⁺¹/(n+1)", "nxⁿ", "xⁿ⁻¹"], correctOptionIndex: 0, solutionText: "Power rule: d/dx(xⁿ) = nxⁿ⁻¹." },
  { text: "If f(x) = x³ - 3x, f'(x) = 0 gives:", options: ["x = ±1", "x = 0", "x = ±3", "x = 3"], correctOptionIndex: 0, solutionText: "f'(x) = 3x² - 3 = 0 → x² = 1 → x = ±1." },
  { text: "The function f(x) = x² is strictly increasing on:", options: ["(0, ∞)", "(-∞, ∞)", "(-∞, 0)", "None"], correctOptionIndex: 0, solutionText: "f'(x)=2x > 0 for x > 0, so strictly increasing on (0,∞)." },
  { text: "∫ cos x dx =", options: ["sin x + C", "-sin x + C", "cos x + C", "-cos x + C"], correctOptionIndex: 0, solutionText: "∫cos x dx = sin x + C." },
  { text: "∫ 1/x dx =", options: ["ln|x| + C", "1/x² + C", "x + C", "-1/x² + C"], correctOptionIndex: 0, solutionText: "∫(1/x)dx = ln|x| + C." },
  { text: "∫₀^(π/2) sin x dx =", options: ["1", "0", "2", "π"], correctOptionIndex: 0, solutionText: "[-cos x]₀^(π/2) = -cos(π/2) + cos(0) = 0 + 1 = 1." },
  { text: "∫₀^1 x² dx =", options: ["1/3", "1/2", "1", "1/4"], correctOptionIndex: 0, solutionText: "[x³/3]₀¹ = 1/3 - 0 = 1/3." },
  { text: "Area between y = x² and y = x (from 0 to 1) is:", options: ["1/6", "1/3", "1/2", "1/4"], correctOptionIndex: 0, solutionText: "∫₀¹(x - x²)dx = [x²/2 - x³/3]₀¹ = 1/2 - 1/3 = 1/6." },
  { text: "Order of the differential equation dy/dx = x + y is:", options: ["1", "2", "0", "3"], correctOptionIndex: 0, solutionText: "Order = order of highest derivative = 1 (dy/dx)." },
  { text: "Solution of dy/dx = y is:", options: ["y = Ceˣ", "y = Ce⁻ˣ", "y = x + C", "y = Cx"], correctOptionIndex: 0, solutionText: "dy/y = dx → ln|y| = x + C → y = Aeˣ." },
  { text: "P(A ∪ B) = P(A) + P(B) when:", options: ["A and B are mutually exclusive", "A and B are independent", "A ⊂ B", "Always"], correctOptionIndex: 0, solutionText: "P(A∪B) = P(A) + P(B) - P(A∩B); if mutually exclusive P(A∩B) = 0." },
  { text: "If P(A) = 0.3, P(B) = 0.4, P(A∩B) = 0.1, then P(A∪B) =", options: ["0.6", "0.7", "0.5", "0.12"], correctOptionIndex: 0, solutionText: "P(A∪B) = 0.3 + 0.4 - 0.1 = 0.6." },
  { text: "Mean of first n natural numbers is:", options: ["(n+1)/2", "n/2", "n(n+1)/2", "n"], correctOptionIndex: 0, solutionText: "Sum = n(n+1)/2; mean = [n(n+1)/2]/n = (n+1)/2." },
  { text: "Standard deviation is the square root of:", options: ["Variance", "Mean", "Range", "Median"], correctOptionIndex: 0, solutionText: "σ = √(Variance); variance = Σ(xᵢ - x̄)²/n." },
  { text: "tan(A + B) = ?", options: ["(tanA + tanB)/(1 - tanA·tanB)", "(tanA - tanB)/(1 + tanA·tanB)", "tanA + tanB", "tanA·tanB"], correctOptionIndex: 0, solutionText: "Compound angle formula: tan(A+B) = (tanA+tanB)/(1-tanAtanB)." },
  { text: "sin 2A = ?", options: ["2 sin A cos A", "sin²A - cos²A", "1 - 2sin²A", "2cos²A - 1"], correctOptionIndex: 0, solutionText: "Double angle: sin 2A = 2 sin A cos A." },
  { text: "cos 2A = ?", options: ["1 - 2sin²A", "2sinA cosA", "sinA cosA", "tan²A - 1"], correctOptionIndex: 0, solutionText: "cos 2A = cos²A - sin²A = 1 - 2sin²A = 2cos²A - 1." },
  { text: "In ΔABC, by sine rule: a/sinA =", options: ["2R", "R", "R/2", "1/R"], correctOptionIndex: 0, solutionText: "Sine rule: a/sinA = b/sinB = c/sinC = 2R (circumradius)." },
  { text: "The number of ways to arrange n objects is:", options: ["n!", "n", "2ⁿ", "nⁿ"], correctOptionIndex: 0, solutionText: "n objects can be arranged in n! (n factorial) ways." },
  { text: "ⁿCr + ⁿCr₋₁ =", options: ["ⁿ⁺¹Cr", "ⁿCr₊₁", "ⁿ⁺¹Cr₋₁", "2·ⁿCr"], correctOptionIndex: 0, solutionText: "Pascal's identity: ⁿCr + ⁿCr₋₁ = ⁿ⁺¹Cr." },
  { text: "Sum of binomial coefficients (1+1)ⁿ =", options: ["2ⁿ", "n!", "n·2ⁿ", "0"], correctOptionIndex: 0, solutionText: "Putting x=1 in (1+x)ⁿ: Σ ⁿCr = 2ⁿ." },
  { text: "nth term of AP: a, a+d, a+2d, ... is:", options: ["a + (n-1)d", "a + nd", "na + d", "a·d^(n-1)"], correctOptionIndex: 0, solutionText: "nth term Tn = a + (n-1)d." },
  { text: "Sum of first n terms of GP with ratio r is:", options: ["a(rⁿ-1)/(r-1) for r≠1", "na for r=0", "arn", "n(a+l)/2"], correctOptionIndex: 0, solutionText: "Sn = a(rⁿ-1)/(r-1) for r≠1; n(a+l)/2 is for AP." },
  { text: "The general term in (x+y)ⁿ expansion is:", options: ["ⁿCr·xⁿ⁻ʳ·yʳ", "ⁿCr·xʳ·yⁿ⁻ʳ", "ⁿPr·xⁿ⁻ʳ·yʳ", "xⁿ⁻ʳ·yʳ"], correctOptionIndex: 0, solutionText: "Tr+1 = ⁿCr·xⁿ⁻ʳ·yʳ (r = 0,1,...,n)." },
  { text: "If z = 3 + 4i, then |z| =", options: ["5", "7", "1", "12"], correctOptionIndex: 0, solutionText: "|z| = √(3² + 4²) = √(9+16) = √25 = 5." },
  { text: "Argument of z = -1 + i√3 is:", options: ["2π/3", "π/3", "π/6", "5π/6"], correctOptionIndex: 0, solutionText: "z = -1 + i√3; r=2, in 2nd quadrant; arg = π - π/3 = 2π/3." },
  { text: "d/dx (eˣ) =", options: ["eˣ", "xeˣ⁻¹", "eˣ/x", "1/eˣ"], correctOptionIndex: 0, solutionText: "eˣ is its own derivative: d/dx(eˣ) = eˣ." },
  { text: "d/dx (ln x) =", options: ["1/x", "ln x / x", "x", "1/x²"], correctOptionIndex: 0, solutionText: "d/dx(ln x) = 1/x (for x > 0)." },
  { text: "The Rolle's theorem requires f(a) = f(b) and f to be:", options: ["Continuous on [a,b] and differentiable on (a,b)", "Differentiable everywhere", "Monotonic", "Periodic"], correctOptionIndex: 0, solutionText: "Rolle's: f continuous on [a,b], differentiable on (a,b), f(a)=f(b) → ∃c: f'(c)=0." },
  { text: "∫ eˣ dx =", options: ["eˣ + C", "eˣ/x + C", "xeˣ + C", "eˣ⁺¹ + C"], correctOptionIndex: 0, solutionText: "∫eˣ dx = eˣ + C." },
  { text: "By integration by parts: ∫ u dv = ?", options: ["uv - ∫v du", "∫u du + ∫v dv", "uv + ∫v du", "u∫dv"], correctOptionIndex: 0, solutionText: "Integration by parts: ∫u dv = uv - ∫v du." },
  { text: "The area enclosed by y = x, x-axis from 0 to 2 is:", options: ["2", "4", "1", "3"], correctOptionIndex: 0, solutionText: "∫₀² x dx = [x²/2]₀² = 2." },
  { text: "lim(x→∞) (1 + 1/x)ˣ =", options: ["e", "1", "∞", "0"], correctOptionIndex: 0, solutionText: "Standard limit: lim(x→∞)(1+1/x)ˣ = e ≈ 2.718." },
  { text: "∫₋ₐᵃ f(x)dx = 0 if f(x) is:", options: ["Odd function", "Even function", "Constant", "Periodic"], correctOptionIndex: 0, solutionText: "For odd function f(-x) = -f(x); symmetric limits cancel → integral = 0." },
];
